package com.example.day03.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.day03.modle.bean.DbBean;

import com.example.day03.db.DbBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dbBeanDaoConfig;

    private final DbBeanDao dbBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dbBeanDaoConfig = daoConfigMap.get(DbBeanDao.class).clone();
        dbBeanDaoConfig.initIdentityScope(type);

        dbBeanDao = new DbBeanDao(dbBeanDaoConfig, this);

        registerDao(DbBean.class, dbBeanDao);
    }
    
    public void clear() {
        dbBeanDaoConfig.clearIdentityScope();
    }

    public DbBeanDao getDbBeanDao() {
        return dbBeanDao;
    }

}
